export const sampleEnquiries = [
  {
    id: "1",
    productName: "Wheat",
    category: "Agriculture",
    destination: "United Arab Emirates",
    expiryDate: "Mar 16, 2024",
    targetPrice: "Negotiable",
    quantity: "MOQ",
    paymentTerms: "Bank to Bank",
    shippingTerms: "Door to Door",
    description:
      "Looking for high-quality wheat suppliers for distribution in UAE.",
    specifications: "Refined\nWheat Flour\nNote: Need distributor within UAE",
    contactPerson: "Yusav Rai",
  },
  {
    id: "2",
    productName: "Solar Panels",
    category: "Energy",
    destination: "India",
    expiryDate: "Mar 20, 2024",
    targetPrice: "$0.45/W",
    quantity: "1000 units",
    paymentTerms: "LC",
    shippingTerms: "FOB",
    description:
      "Seeking Tier 1 solar panel manufacturers for residential projects.",
    specifications:
      "- Minimum efficiency: 20%\n- Size: 60 cell\n- Power output: 330W+",
    contactPerson: "Amit Shah",
  },
  {
    id: "3",
    productName: "Cotton Yarn",
    category: "Textiles",
    destination: "Bangladesh",
    expiryDate: "Apr 10, 2024",
    targetPrice: "Negotiable",
    quantity: "50,000 kg",
    paymentTerms: "Advance Payment",
    shippingTerms: "CIF",
    description:
      "Looking for high-quality cotton yarn suppliers for garment production.",
    specifications: "Combed\nRing Spun\nCount: 30s",
    contactPerson: "Rahim Uddin",
  },
  {
    id: "4",
    productName: "LED Light Bulbs",
    category: "Electronics",
    destination: "South Africa",
    expiryDate: "Apr 5, 2024",
    targetPrice: "$1.20/unit",
    quantity: "10,000 units",
    paymentTerms: "Net 30",
    shippingTerms: "EXW",
    description:
      "Seeking suppliers for energy-efficient LED light bulbs for retail distribution.",
    specifications: "Warm White\n10W\n800 Lumens",
    contactPerson: "Nkosi Dlamini",
  },
  {
    id: "5",
    productName: "Organic Apples",
    category: "Food & Beverage",
    destination: "Germany",
    expiryDate: "Mar 28, 2024",
    targetPrice: "Negotiable",
    quantity: "20 tons",
    paymentTerms: "D/P",
    shippingTerms: "Door to Door",
    description:
      "Looking for organic apple suppliers for wholesale distribution in Germany.",
    specifications: "Grade A\nRed Delicious\nCertified Organic",
    contactPerson: "Karl Muller",
  },
  {
    id: "6",
    productName: "Steel Pipes",
    category: "Construction",
    destination: "Saudi Arabia",
    expiryDate: "Apr 15, 2024",
    targetPrice: "Market Price",
    quantity: "500 metric tons",
    paymentTerms: "TT",
    shippingTerms: "FOB",
    description:
      "Requirement for high-grade steel pipes for an infrastructure project.",
    specifications: "Seamless\nGrade: API 5L X52\nLength: 12m",
    contactPerson: "Fahad Al-Saud",
  },
];
